services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Проброс порта PostgreSQL на хост
    networks:
      - odoo-net

  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo_data:/var/lib/odoo
    networks:
      - odoo-net

volumes:
  db_data:
  odoo_data:

networks:
  odoo-net:
    driver: bridge
